import type { Metadata } from "next";
import "./globals.css";
// import NavBar from "@/components/navbar.component";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="bg-custom-white-50">
			{/* <NavBar /> */}
			<body>{children}</body>
		</html>
	);
}
